services:
  - type: web
    name: gestion-equipos
    env: python
    plan: free
    buildCommand: bash render-build.sh && pip install -r requirements.txt
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
